-- 코드를 작성해주세요
SELECT O.ITEM_ID, O.ITEM_NAME, O.RARITY
FROM ITEM_INFO AS O LEFT JOIN (
    SELECT PARENT_ITEM_ID, COUNT(PARENT_ITEM_ID) AS COUNT
    FROM ITEM_TREE
    GROUP BY PARENT_ITEM_ID
    ) AS T ON O.ITEM_ID = T.PARENT_ITEM_ID
WHERE T.PARENT_ITEM_ID IS NULL
ORDER BY O.ITEM_ID DESC