-- 코드를 작성해주세요
SELECT O.ID, IFNULL(T.CHILD_COUNT,0) AS CHILD_COUNT
FROM ECOLI_DATA AS O LEFT JOIN (
    SELECT PARENT_ID AS ID, COUNT(PARENT_ID) AS CHILD_COUNT
    FROM ECOLI_DATA 
    GROUP BY PARENT_ID
    ) AS T ON O.ID = T.ID
