-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES,I.ADDRESS, T.SCORE
FROM REST_INFO AS I JOIN (
    SELECT R.REST_ID,ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE
    FROM REST_REVIEW AS R
    GROUP BY R.REST_ID
    ) AS T ON I.REST_ID = T.REST_ID
WHERE I.ADDRESS LIKE '서울%'
ORDER BY T.SCORE DESC, I.FAVORITES DESC