-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME,  P.TOTAL_SALES
FROM (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS ='DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000
    ) AS P LEFT JOIN USED_GOODS_USER AS U ON P.WRITER_ID = U.USER_ID
ORDER BY P.TOTAL_SALES ASC
