SELECT YEAR(E.DIFFERENTIATION_DATE)AS YEAR, (A.SIZE - E.SIZE_OF_COLONY)AS YEAR_DEV, ID
FROM ECOLI_DATA E JOIN ( SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE
                       FROM ECOLI_DATA
                       group by  YEAR(DIFFERENTIATION_DATE) ) A
                        ON YEAR(E.DIFFERENTIATION_DATE) = A.YEAR
ORDER BY YEAR, YEAR_DEV